# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: gosyncit-tests

on:
  push:
    #branches: ["master"]
    tags:
      - "*"
  pull_request:
    branches: ["master"]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.21.4"
          go-package: ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
